language: node_js
before_install: sudo apt-get -y install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libxext6
install: npm install
script: npm run test:ci
before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: now --token $NOW_TOKEN --public ./storybook-static && now alias decentraland-ui --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
node_js:
  - "node"
cache:
  directories:
    - node_modules