# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9.11.1

    working_directory: /tmp/ui

    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - run: 
          name: Run snapshot tests
          command: npm run test:coverage
      - run: 
          name: Send coverage reports
          command: npm run codecov
      - run: 
          name: Build static storybook
          command: npm run build:storybook
      - run: 
          name: Run visual tests
          command: npm run test:visual
workflows:
  version: 2
  test:
    jobs:
      - test